name: Create Production Builds

on:
  push:
    branches: ['main']

jobs:
  build_android:
    type: build
    params:
      platform: android

  build_ios:
    type: build
    params:
      platform: ios

  deploy_web:
    type: deploy
    params:
      platform: web
